// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwwiVMKM-gmBvPo-OsARJAqdZhcAUR1Dg',
    appId: '1:400498672703:web:05e5d1ae6343af247d248a',
    messagingSenderId: '400498672703',
    projectId: 'brew-crew-8280f',
    authDomain: 'brew-crew-8280f.firebaseapp.com',
    storageBucket: 'brew-crew-8280f.appspot.com',
    measurementId: 'G-X9QJFSEVY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPAXO7hkgRlCw62n9WJn_mCSkKnF3vkGc',
    appId: '1:400498672703:android:19a0588589ea46357d248a',
    messagingSenderId: '400498672703',
    projectId: 'brew-crew-8280f',
    storageBucket: 'brew-crew-8280f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTJT2JwbsaCmNTkTb7_AqImjmuxtswn4',
    appId: '1:400498672703:ios:cde454ebff7d60b17d248a',
    messagingSenderId: '400498672703',
    projectId: 'brew-crew-8280f',
    storageBucket: 'brew-crew-8280f.appspot.com',
    iosClientId: '400498672703-5j6n45igenjbfgr7v8c4lmgpv143n9hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewcrewFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTJT2JwbsaCmNTkTb7_AqImjmuxtswn4',
    appId: '1:400498672703:ios:cde454ebff7d60b17d248a',
    messagingSenderId: '400498672703',
    projectId: 'brew-crew-8280f',
    storageBucket: 'brew-crew-8280f.appspot.com',
    iosClientId: '400498672703-5j6n45igenjbfgr7v8c4lmgpv143n9hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewcrewFirebase',
  );
}
